CREATE TABLE IF NOT EXISTS "Conversations" (
    id SERIAL PRIMARY KEY,
    "favoriteList" BOOLEAN DEFAULT FALSE,
    "blackList" BOOLEAN DEFAULT FALSE,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);